@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
    <div class="container d-flex flex-column justify-content-center align-items-center" style="padding-top: 30px; padding-bottom: 50px; font-size: 0.8rem;">
        <h1 class="text-center mb-4" style="font-weight: bold;">Welcome to the Dashboard!</h1>
        
        <div class="w-75">
            <!-- Tasks for Admin -->
            <h2 class="mt-4 mb-3" style="font-weight: bold;">Tasks for Admin</h2>
            
            <!-- Manage Users Table -->
            <h3 class="mt-3 mb-2" style="font-weight: normal;">Manage Users</h3>
            <table class="table table-dark table-bordered mb-5">
                <thead>
                    <tr>
                        <th>User ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th>Last Voted</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- No data yet -->
                </tbody>
            </table>

            <!-- View Reports Table -->
            <h3 class="mt-4 mb-2" style="font-weight: normal;">View Reports</h3>
            <table class="table table-dark table-bordered mb-5">
                <thead>
                    <tr>
                        <th>Report ID</th>
                        <th>Title</th>
                        <th>Generated By</th>
                        <th>Date Created</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- No data yet -->
                </tbody>
            </table>

            <!-- View Voting Results Table -->
            <h3 class="mt-4 mb-2" style="font-weight: normal;">View Voting Results</h3>
            <table class="table table-dark table-bordered mb-5">
                <thead>
                    <tr>
                        <th>Candidate</th>
                        <th>Party Affiliation</th>
                        <th>Election Position</th>
                        <th>Votes</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- No data yet -->
                </tbody>
            </table>

            <!-- Larger Space Between Admin and Organizer Tasks -->
            <div class="my-5" style="height: 100px;"></div>

            <!-- Tasks for Organizer -->
            <h2 class="mt-4 mb-3" style="font-weight: bold;">Tasks for Organizer</h2>
            
            <!-- Manage Events Table -->
            <h3 class="mt-3 mb-2" style="font-weight: normal;">Manage Events</h3>
            <table class="table table-dark table-bordered mb-5">
                <thead>
                    <tr>
                        <th>Event ID</th>
                        <th>Event Name</th>
                        <th>Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- No data yet -->
                </tbody>
            </table>

            <!-- View Voting Results Table -->
            <h3 class="mt-4 mb-2" style="font-weight: normal;">View Voting Results</h3>
            <table class="table table-dark table-bordered mb-5">
                <thead>
                    <tr>
                        <th>Candidate</th>
                        <th>Party Affiliation</th>
                        <th>Election Position</th>
                        <th>Votes</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- No data yet -->
                </tbody>
            </table>
        </div>
    </div>
@endsection
